name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      # Uncomment if you add linting later
      # - name: Lint
      #   run: npm run lint

      # Uncomment if you add tests later
      # - name: Test
      #   run: npm test

      - name: Build
        run: npm run build